vertical_tabs_config.visibility:
  path: 'admin/config/user-interface/vertical_tabs_config'
  defaults: 
    _form: 'Drupal\vertical_tabs_config\Form\VisibilityConfigurationForm'
    _title: 'Vertical tabs visibility'
  requirements:
    _permission: 'administer site configuration'
    
vertical_tabs_config.order:
  path: 'admin/config/user-interface/vertical_tabs_config/order'
  defaults: 
    _form: 'Drupal\vertical_tabs_config\Form\OrderConfigurationForm'
    _title: 'Vertical tabs order'
  requirements:
    _permission: 'administer site configuration'
