vertical_tabs_config.visibility:
  title: Vertical tabs visibility
  route_name: vertical_tabs_config.visibility
  base_route: vertical_tabs_config.visibility
    
vertical_tabs_config.order:
  title: Vertical tabs order
  route_name: vertical_tabs_config.order
  base_route: vertical_tabs_config.visibility
